exclude: |
  (?x)^(
      pzp/data/.*
  )$

repos:
  # XML canonicalize
  - repo: local
    hooks:
      - id: canonicalize-xml
        name: Canonicalize XML
        entry: scripts/canonicalize_xml.py
        language: python
        files: '\.(xml|qlr|qml|qgs)$'
        pass_filenames: true
        additional_dependencies: ["lxml"]

  # Fix end of files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - "--fix=lf"

  # Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  # Remove unused imports/variables
  - repo: git@github.com:myint/autoflake.git
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - "--in-place"
          - "--remove-all-unused-imports"
          - "--remove-unused-variable"

  # Sort imports
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args:
          - -m
          - "3"
          - -l
          - "88"
          - --trailing-comma
          - --known-local-folder
          - coanse

  # Black formatting
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length", "120"]

  # Python flake8
  - repo: https://github.com/pycqa/flake8
    rev: "7.2.0"
    hooks:
      - id: flake8
        args:
          - --ignore=E203,E402,E501,W291,W503
          - --max-line-length=120
