version: '3.7'

services:
  qgis:
    image: "opengisch/qgis:focal-3.16"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix ro
      - /home/mario/projects/pzp/pzp/pzp:/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pzp/
      - /home/mario/projects/pzp-utils/pzp_utils/:/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pzp_utils/
    command:
      - qgis
    environment:
      - DISPLAY=${DISPLAY}
    privileged: true
    network_mode: host
